
arch: amd64
os: linux
dist: bionic
language: python
jobs:
  include:
    - stage: linter
      name: "Python 3.6"
      python: 3.6
      install:
        - pip install -U pip setuptools wheel
        - pip install -r requirements.txt
        - pip install -r requirements-ci.txt
      script:
        - flake8 .
    - stage: linter
      name: "Python 3.7"
      python: 3.7
      install:
        - pip install -U pip setuptools wheel
        - pip install -r requirements.txt
        - pip install -r requirements-ci.txt
      script:
        - flake8 .
    - stage: linter
      name: "Python 3.8"
      python: 3.8
      install:
        - pip install -U pip setuptools wheel
        - pip install -r requirements.txt
        - pip install -r requirements-ci.txt
      script:
        - flake8 .
    - stage: linter
      name: "Python 3.8"
      python: 3.8
      install:
        - pip install -U pip setuptools wheel
        - pip install -r requirements.txt
        - pip install -r requirements-ci.txt
      script:
        - flake8 .
    - stage: build
      name: "Build Release - Linux"
      python: 3.8
      install:
        - pip install -U pip setuptools wheel
        - pip install -r requirements.txt
        - pip install -r requirements-ci.txt
      script:
        - pyinstaller mocos-gui.py
        - cp -r views dist/mocos-gui/
        - zip -r mocos-gui-linux-amd64.zip dist/mocos-gui/
      deploy:
        provider: releases
        api_key: $API_TOKEN
        file_glob: true
        file: ./*.zip
        skip_cleanup: true
        draft: true
    - stage: build
      name: "Build Release - Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version=3.8
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - pip install -U setuptools wheel
        - pip install -r requirements.txt
        - pip install -r requirements-ci.txt
      script:
        - pyinstaller mocos-gui.py
        - cp -r views dist/mocos-gui/
        - 7z a -tzip mocos-gui-win-amd64.zip dist/mocos-gui/
      deploy:
        provider: releases
        api_key: $API_TOKEN
        file_glob: true
        file: ./*.zip
        skip_cleanup: true
        draft: true